// "use client"
import { Inter } from "next/font/google";
import "./globals.css";
// import { motion, AnimatePresence } from "framer-motion";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Academics and Career Council | IIT Kanpur",
  description: "Generated by create next app",
  icons: {
    icon: [

      'public/favicon.ico'
    ]
    
  }
  
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en" className="scroll-smooth">
      
      <body className={inter.className}>{children}
      <Footer/>
      </body>
    </html>
  );
}
